FROM hadonga/bevdet_ros:0.1
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Seoul

# set userinfo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y x11-xserver-utils wget
