version: '1.0'

services:
  bevdet_ros:
    container_name: bevdet_ros_$USER
    image: bevdet_ros_$USER
    build:
      context: ./
      dockerfile: dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu, compute, utility, graphics ]
    volumes:
      - ../:/bevdet_ros
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ~/.Xauthority:/root/.Xauthority:ro
    network_mode: host
    environment:
      - "DISPLAY"
      - "LIBGL_ALWAYS_INDIRECT=1"
    # command: tail -f /dev/null
    tty: true
    ipc: host
    privileged: true
