FROM ytwanghaoyu/bevdet:bevdet-6c75bb4e-fix
# FROM nvcr.io/nvidia/tensorrt:23.01-py3

# https://docs.nvidia.com/deeplearning/tensorrt/container-release-notes/index.html 
# TensorRT 8.5.2.2
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get -y install software-properties-common libzmq3-dev